<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="SonarAnalyzer.CSharp" Version="10.34.0.3385">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
