name: 'middle_project'

services:
  data_injector:
    container_name: data_injector
    image: feelitbreak/middle_project:data-injector-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8082
    ports:
      - 8082:8082
      - 8083:8083
  watchtower:
    container_name: watchtower
    image: nickfedor/watchtower
    restart: unless-stopped
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=60
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock