// <auto-generated />
using System;
using DataProcessorService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataProcessorService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MeterReadingsDbContext))]
    [Migration("20260904112705_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DataProcessorService.Domain.Entities.MeterReading", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CollectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("collected_at");

                    b.Property<int>("SensorId")
                        .HasColumnType("integer")
                        .HasColumnName("sensor_id");

                    b.Property<string>("sensor_type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("CollectedAt", "Id")
                        .HasDatabaseName("ix_meter_readings_collected_id");

                    b.HasIndex("SensorId", "CollectedAt")
                        .IsUnique()
                        .HasDatabaseName("ux_meter_readings_sensor_collected");

                    b.HasIndex("sensor_type", "CollectedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_meter_readings_type_collected_desc");

                    b.ToTable("meter_readings", (string)null);

                    b.HasDiscriminator<string>("sensor_type").HasValue("MeterReading");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("DataProcessorService.Domain.Entities.Sensor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("sensor_type");

                    b.HasKey("Id");

                    b.HasIndex("Name", "Type")
                        .IsUnique()
                        .HasDatabaseName("ux_sensors_name_type");

                    b.ToTable("sensors", (string)null);
                });

            modelBuilder.Entity("DataProcessorService.Domain.Entities.AirQualityReading", b =>
                {
                    b.HasBaseType("DataProcessorService.Domain.Entities.MeterReading");

                    b.Property<int>("Co2")
                        .HasColumnType("integer")
                        .HasColumnName("co2");

                    b.Property<int>("Humidity")
                        .HasColumnType("integer")
                        .HasColumnName("humidity");

                    b.Property<int>("Pm25")
                        .HasColumnType("integer")
                        .HasColumnName("pm25");

                    b.HasDiscriminator().HasValue("air_quality");
                });

            modelBuilder.Entity("DataProcessorService.Domain.Entities.EnergyReading", b =>
                {
                    b.HasBaseType("DataProcessorService.Domain.Entities.MeterReading");

                    b.Property<double>("EnergyKwh")
                        .HasColumnType("double precision")
                        .HasColumnName("energy_kwh");

                    b.HasDiscriminator().HasValue("energy");
                });

            modelBuilder.Entity("DataProcessorService.Domain.Entities.MotionReading", b =>
                {
                    b.HasBaseType("DataProcessorService.Domain.Entities.MeterReading");

                    b.Property<bool>("MotionDetected")
                        .HasColumnType("boolean")
                        .HasColumnName("motion_detected");

                    b.HasDiscriminator().HasValue("motion");
                });

            modelBuilder.Entity("DataProcessorService.Domain.Entities.MeterReading", b =>
                {
                    b.HasOne("DataProcessorService.Domain.Entities.Sensor", "Sensor")
                        .WithMany("Readings")
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("DataProcessorService.Domain.Entities.Sensor", b =>
                {
                    b.Navigation("Readings");
                });
#pragma warning restore 612, 618
        }
    }
}
