name: Data Injector Service - Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./DataInjectorService/DataInjectorService
    steps:
    - uses: actions/checkout@v6
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '10.0.x'
    - name: Cache NuGet packages
      uses: actions/cache@v5
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
    - name: Cache SonarQube packages
      uses: actions/cache@v5
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
    - name: Install SonarQube scanner
      run:
        dotnet tool update --global dotnet-sonarscanner
    - name: Build and analyze
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        dotnet restore
        dotnet-sonarscanner begin /k:"feelitbreak_MiddleProject" /o:"feelitbreak" /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
        dotnet build --no-restore
        dotnet test --no-build --verbosity normal
        dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"