name: Data Injector Service - Build & Publish

on:
  push:
    branches:
      - main
    paths:
      - 'DataInjectorService/**'
  pull_request:
    paths:
      - 'DataInjectorService/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./DataInjectorService/DataInjectorService
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '10.0.x'
    - name: Cache NuGet packages
      uses: actions/cache@v5
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
    - name: Cache SonarQube packages
      uses: actions/cache@v5
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
    - name: Install .NET tools
      run: |
        dotnet tool update --global dotnet-coverage
        dotnet tool update --global dotnet-sonarscanner
    - name: Build and Analyze
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        dotnet restore
        dotnet format DataInjectorService.slnx --verify-no-changes --verbosity diagnostic
        dotnet-sonarscanner begin \
          /k:"feelitbreak_MiddleProject_DataInjectorService" \
          /n:"Data Injector Service" \
          /o:"feelitbreak" \
          /d:sonar.token="${{ secrets.SONAR_TOKEN_DATA_INJECTOR }}" \
          /d:sonar.cs.vscoveragexml.reportsPaths=coverage.xml \
          /d:sonar.projectBaseDir="$GITHUB_WORKSPACE/DataInjectorService"
        dotnet build --no-restore
        dotnet-coverage collect "dotnet test --no-build --verbosity normal" -f xml -o "coverage.xml"
        dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN_DATA_INJECTOR }}"
  publish:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v4
      with:
        username: ${{ vars.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v4
    - name: Build and Push
      uses: docker/build-push-action@v7
      with:
        context: "{{defaultContext}}:DataInjectorService/DataInjectorService"
        push: true
        tags: ${{ vars.DOCKERHUB_REPOSITORY }}:data-injector-service